services:
    oro_datasnap.process_executor:
        public: false
        class: 'Oro\Component\Database\Service\ProcessExecutor'

    oro_datasnap.engine.pdo_mysql:
        class: 'Oro\Component\Database\Engine\MysqlDatabaseEngine'
        public: false
        arguments:
            - '@oro_datasnap.process_executor'
        tags:
            - {name: oro.database.engine, alias: pdo_mysql, priority: 100}

    oro_datasnap.engine.pdo_pgsql:
        class: 'Oro\Component\Database\Engine\PgsqlDatabaseEngine'
        public: false
        arguments:
            - '@oro_datasnap.process_executor'
        tags:
            - {name: oro.database.engine, alias: pdo_pgsql, priority: 100}

    oro_datasnap.engine.registry:
        class: 'Oro\Component\Database\Service\DatabaseEngineRegistry'
        lazy: true
        #TODO : replace with compiller pass with priorities
        calls:
            - ['addEngine',['@oro_datasnap.engine.pdo_mysql', 'pdo_mysql']]
            - ['addEngine',['@oro_datasnap.engine.pdo_pgsql', 'pdo_pgsql']]
